language: python
python:
  - "3.5.0"
# command to install dependencies
install:
  - pip install -r docs/requirements/travis.dep
  - pip install cov-core
  - pip install coveralls
  - pip install nose2
# command to run tests
script:
  - nose2 --with-coverage
  - cd docs && make gh-pages

after_success:
  coveralls
