language: python
python:
  - "3.5.0"
# command to install dependencies
install:
  - pip install .
  - pip install cov-core
  - pip install coveralls
  - pip install nose2
# command to run tests
script:
  - nose2 --with-coverage

after_success:
  coveralls
